version: 2

reference:
  store_artifacts: &store_artifacts
    store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      path: /tmp/artifacts
      destination: artifacts
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
        auth:
          username: bastilion
          password: $DOCKERHUB_PASSWORD
    environment:
      # See https://github.com/opendatakit/collect/blob/master/.circleci/config.yml#L86-L92 for -Xm[sx]
      # Disable pre-dexing because we don't need incremental builds here and it just slows the process down.
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms128m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError" -DpreDexEnable=false'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build debug APK
          command: |
            ./gradlew -PversionNumber=$(.circleci/get_version) assembleDebug
            mkdir -p /tmp/artifacts
            cp app/build/outputs/apk/debug/app-debug.apk /tmp/artifacts/DE4LRoadTracker-$(.circleci/get_version).apk
      - *store_artifacts
      - persist_to_workspace:
          root: /tmp
          paths: artifacts
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
        auth:
          username: bastilion
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Publish Release on GitHub
          command: |
            VERSION=$(ls /tmp/artifacts/*.apk | sed -e 's/.*-//' -e 's/\.apk*//')
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/artifacts

workflows:
  version: 2
  android-debug-build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build
